name: ocr_scan_text
description: OCR Scan Text is a wrapper around the "Google ML kit Text Recognition" library.
version: 1.3.1
homepage: https://github.com/boursorama/ocr_scan_text

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  google_mlkit_text_recognition: ^0.8.1
  camera: ^0.10.2+1
  image: ^4.0.17
  pdf_render: ^1.4.0
  path: ^1.8.2
  path_provider: ^2.0.15
  file_picker: ^5.0.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.boursorama.ocr_scan_text.ocr_scan_text
        pluginClass: OcrScanTextPlugin
      ios:
        pluginClass: OcrScanTextPlugin
